### ISSUE TITLE
Error in Advance(Auth) 

### ISSUE THREAD

**Issue by mehmetsefabalik** [jirawatee/FirebaseRealtimeDatabase-Android#1]
I tried to run app , Basic(No Auth) is working correctly but Advance(Auth) crashes. Here is my log:

`A/FirebaseApp: Firebase API initialization failure.
                                                java.lang.reflect.InvocationTargetException
                                                    at java.lang.reflect.Method.invokeNative(Native Method)
 Caused by: java.lang.IllegalArgumentException: Given String is empty or null`

this line causes exception: 
`mAuth = FirebaseAuth.getInstance();`

How to solve it?

**Comment by jirawatee** [comment]
@mehmetsefa2644 Sorry for replying late. I try to run it again but I can't find this error. Please make sure you add the correctly play-services.json in app/
